### ISSUE TITLE
Frontend: Complete the login process from the frontend.

### ISSUE THREAD

**Issue by mrsbluerose** [savvato-software/savvato-work-app-frontend-app#3]
- Create an endpoint which accepts a username and password. 
  - Done, this is the /public/login endpoint on the backend

- It returns something to the front end.
  - Mostly done, it returns an object with user's username and actual name. The token will appear in the header, soon. TBD Prakirth.
- The frontend save the token in browser session storage.

UPDATE
incorporate testing (jasmin and/or karma)

**Comment by mrsbluerose** [comment]
pull request: [https://github.com/savvato-software/savvato-work-app-frontend-app/pull/15](https://github.com/savvato-software/savvato-work-app-frontend-app/pull/15)

**Comment by mrsbluerose** [comment]
pull request: [https://github.com/savvato-software/savvato-work-app-frontend-app/pull/15](https://github.com/savvato-software/savvato-work-app-frontend-app/pull/15)

**Comment by haxwell** [comment]
Need to make the actual call to the backend.

**Comment by haxwell** [comment]
There will need to be properties added to the environment file, for the protocol, domain, and port portion of the URL. 

These properties are to be used when creating a call to the backend. For instance, the fetch call presently in the login code calls '/public/login', but it needs to call, and similarly all backends calls need to call, `environment.domain + "/public/login"`, for example.

You can look at how this is done in our other project tribe-app, by looking at the `environment.*.ts` files, and how the property is used there.
